seg 20 jan 2025 19:18:17 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-runimage b/chili-runimage
--- a/chili-runimage
+++ b/chili-runimage
@@ -4,8 +4,9 @@
 #  chili-runimage
 #  Created: 2023/04/25
 #  Altered: qua 14 fev 2024 11:05:21 -04
+#  Updated: sex 03 jan 2025 23:06:19 -04
 #
-#  Copyright (c) 2023-2024, Vilmar Catafesta <vcatafesta@gmail.com>
+#  Copyright (c) 2023-2025, Vilmar Catafesta <vcatafesta@gmail.com>
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -50,7 +51,7 @@
 export TEXTDOMAINDIR=/usr/share/locale
 export TEXTDOMAIN=chili-runimage
 #export XDG_RUNTIME_DIR ; XDG_RUNTIME_DIR=/run/user/$(id -g)
-sudo cp ~/.config/pulse/cookie /root/.config/pulse/cookie > /dev/null 2>&-
+sudo cp ~/.config/pulse/cookie /root/.config/pulse/cookie >/dev/null 2>&-
 
 #debug
 export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
@@ -61,15 +62,18 @@ export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
 readonly APP="${0##*/}"
 readonly _VERSION_='1.5.01-20240214'
 readonly DEPENDENCIES=('tput' 'printf' 'qemu-system-x86_64' 'gettext')
-readonly PACKAGEDEP=([tput]='ncurses' [printf]='coreutils' [qemu-system-x86_64]='qemu' [gettext]='gettext')
+readonly PACKAGEDEP=([tput]='ncurses' [printf]='coreutils' [qemu - system - x86_64]='qemu' [gettext]='gettext')
+#readonly iface_bridge='docker0'
+#readonly iface_bridge='virbr0'
 readonly iface_bridge='br0'
-declare xmem='4G'
-#declare audioserver='pulseaudio'
-#declare videodevice='virtio-vga'
-declare audioserver='alsa'
+declare xmem='8G'
+declare audioserver='auto'
+declare videodevice='virtio-vga'
+declare videodevice='qxl'
 declare videodevice='VGA'
-declare -i uefi=0
-declare -i bridge=0
+declare bridge=false
+declare uefi=false
+declare drive=false
 declare -a qemu_options=()
 trap cleanup_working_dir EXIT
 
@@ -80,18 +84,18 @@ function cleanup_working_dir {
 }
 
 function sh_debug() {
-    whiptail \
-        --fb \
-        --clear \
-        --backtitle "[debug]$0" \
-        --title "[debug]$0" \
-        --yesno "${*}\n" \
-        0 40
-    result=$?
-    if ((result)); then
-        exit
-    fi
-    return $result
+	whiptail \
+		--fb \
+		--clear \
+		--backtitle "[debug]$0" \
+		--title "[debug]$0" \
+		--yesno "${*}\n" \
+		0 40
+	result=$?
+	if ((result)); then
+		exit
+	fi
+	return $result
 }
 export -f sh_debug
 
@@ -190,12 +194,47 @@ function sh_checkDependencies {
 	fi
 }
 
+detect_audio_server() {
+  if pgrep -x pipewire >/dev/null; then
+    echo "pipewire"
+  elif pgrep -x pulseaudio >/dev/null; then
+    echo "pa"
+  elif pgrep -x jackd >/dev/null; then
+    echo "jack"
+  else
+    echo "none"
+  fi
+}
+
+function sh_set_qemu_common_options {
+	qemu_options+=(-no-fd-bootchk)
+	qemu_options+=(-cpu host)
+  qemu_options+=(-machine accel=kvm)
+	qemu_options+=(-smp "$(nproc)")
+	qemu_options+=(-name 'chili-runimage')
+	qemu_options+=(-device "$videodevice")
+	qemu_options+=(-display gtk,gl=on)
+	qemu_options+=(-device intel-hda)
+	[[ "$audioserver" = 'auto' ]] && audioserver="$(detect_audio_server)"
+  qemu_options+=(-audiodev "$audioserver",id=snd0)
+	qemu_options+=(-device hda-duplex,audiodev=snd0,mixer=off)
+	qemu_options+=(-rtc base=localtime,clock=host)
+	qemu_options+=(-device ich9-intel-hda)
+	qemu_options+=(-device hda-output,audiodev=snd0)
+	qemu_options+=(-global ICH9-LPC.disable_s3=1)
+	qemu_options+=(-machine type=q35,smm=on,accel=kvm,usb=on,pcspk-audiodev=snd0)
+	qemu_options+=(-serial stdio)
+}
+
 function filerun_bios {
 	if test $# -ge 1; then
-		if test -r $1; then
-			#			qemu-system-x86_64 -drive file=${1},format=raw,if=none,id=disk1 -device ide-hd,drive=disk1,bootindex=1 -device virtio-scsi-pci,id=scsi0 "${qemu_options[@]}"
-			#			qemu-system-x86_64 -drive file=${1},format=raw,index=0,media=disk,if=none,id=disk1 -device ide-hd,drive=disk1,bootindex=1 -device virtio-scsi-pci,id=scsi0 "${qemu_options[@]}"
-			qemu-system-x86_64 -drive file=${1},format=raw,media=disk,if=none,id=disk1 -device ide-hd,drive=disk1,bootindex=1 -device virtio-scsi-pci,id=scsi0 "${qemu_options[@]}"
+		if test -e $1; then
+      mkdir -p /run/user/$(id -u)
+      chmod 700 /run/user/$(id -u)
+      export XDG_RUNTIME_DIR=/run/user/0
+      qemu_options+=(-drive file=${1},format=raw,media=disk,if=none,id=disk1)
+      qemu_options+=(-device ide-hd,drive=disk1,bootindex=1 -device virtio-scsi-pci,id=scsi0)
+      sudo env XDG_RUNTIME_DIR=/run/user/$(id -u) qemu-system-x86_64 "${qemu_options[@]}"
 		else
 			log_msg "${red}ERROR: ${cyan}'$1' ${red}$(gettext "erro de leitura ou não existe")"
 		fi
@@ -205,127 +244,77 @@ function filerun_bios {
 }
 
 function filerun_uefi {
+  local input_file=$(readlink -f "$1")
 	local ovmf_code
 	local ovmf_vars
-   	local working_dir
-    local cpath_edk2=('/usr/share/edk2/x64' '/usr/share/edk2-ovmf/x64')
-    local cpath
+	local working_dir
+	local cpath_edk2=('/usr/share/edk2/x64')
+	local cpath
 
 	if test $# -ge 1; then
-		if test -r $1; then
-		    for cpath in "${cpath_edk2[@]}"; do
-	    		if [[ -f "$cpath/OVMF_CODE.fd" ]]; then
-        			ovmf_code="$cpath/OVMF_CODE.fd"
-	        		ovmf_vars="$cpath/OVMF_VARS.fd"
-	    		    break
-    		    fi
-		    done
+		if test -e "$input_file"; then
+			for cpath in "${cpath_edk2[@]}"; do
+				if [[ -f "$cpath/OVMF_CODE.4m.fd" ]]; then
+					ovmf_code="$cpath/OVMF_CODE.4m.fd"
+					ovmf_vars="$cpath/OVMF_VARS.4m.fd"
+					break
+				fi
+			done
 
 			if [[ -z $ovmf_code ]]; then
-				printf 'ERROR: %s\n' "OVMF_VARS.fd $(gettext "não encontrado. Instale o pacote") edk2-ovmf."
+				printf 'ERROR: %s\n' "OVMF_CODE.4m.fd $(gettext "não encontrado. Instale o pacote") edk2-ovmf."
 				exit 1
 			fi
 
-            working_dir="$(mktemp -dt chili-runimage-$USER.XXX)"
-			cp -av -- $ovmf_vars "${working_dir}/" > /dev/null 2>&-
-
-			if [[ ${1: -4} == ".iso" ]]; then
-				# ISO disk
-				qemu-system-x86_64 \
-					-cdrom $1 \
-					-boot d \
-					-drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=on \
-					-drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.fd \
-					"${qemu_options[@]}"
-			else
-				# RAW disk
-				qemu-system-x86_64 \
-					-drive file=${1},format=raw,if=virtio \
-					-drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=on \
-					-drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.fd \
-					"${qemu_options[@]}"
+			if [[ -z $ovmf_vars ]]; then
+				printf 'ERROR: %s\n' "OVMF_VARS.4m.fd $(gettext "não encontrado. Instale o pacote") edk2-ovmf."
+				exit 1
 			fi
+
+      #working_dir="$(mktemp -dt chili-runimage-$USER-$(date +%Y%m%d-%H%M%S))"
+      working_dir="/tmp/chili-runimage-$USER-$(date +%Y%m%d-%H%M%S)"
+      mkdir -p "$working_dir"
+      #trap "rm -rf $working_dir" EXIT
+
+      cp -av -- "$ovmf_vars" "${working_dir}/" >/dev/null 2>&1 || {
+        printf 'ERROR: %s\n' "$(gettext "Erro ao copiar OVMF_VARS. Verifique permissões ou espaço em disco.")"
+        exit 1
+      }
+
+      chmod 644 "${working_dir}/OVMF_VARS.4m.fd"
+
+      mkdir -p /run/user/$(id -u)
+      chmod 700 /run/user/$(id -u)
+      export XDG_RUNTIME_DIR=/run/user/$(id -u)
+      if [[ ${input_file: -4} == ".iso" ]]; then
+        # ISO disk
+        qemu_options+=(-drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=on)
+        qemu_options+=(-drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.4m.fd)
+        qemu_options+=(-cdrom "$input_file")
+        qemu_options+=(-boot d)
+        #sudo -u $USER env XDG_RUNTIME_DIR=/run/user/$(id -u) qemu-system-x86_64 "${qemu_options[@]}"
+        sudo env XDG_RUNTIME_DIR=/run/user/$(id -u) qemu-system-x86_64 "${qemu_options[@]}"
+      elif [[ ${input_file: -6} == ".qcow2" ]]; then
+        # QCOW2 disk
+        qemu_options+=(-drive file="$input_file",format=qcow2,if=virtio)
+        qemu_options+=(-drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=on)
+        qemu_options+=(-drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.4m.fd)
+        sudo env XDG_RUNTIME_DIR=/run/user/$(id -u) qemu-system-x86_64 "${qemu_options[@]}"
+      else
+        # RAW disk
+        qemu_options+=(-drive file="$input_file",format=raw,if=virtio)
+        qemu_options+=(-drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=on)
+        qemu_options+=(-drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.4m.fd)
+        sudo env XDG_RUNTIME_DIR=/run/user/$(id -u) qemu-system-x86_64 "${qemu_options[@]}"
+      fi
 		else
-			log_msg "${red}ERROR: ${cyan}'$1' ${red}$(gettext "erro de leitura ou não existe")"
+			log_msg "${red}ERROR: ${cyan}'$1' ${red}$(gettext "O arquivo $1 não pode ser lido. Verifique se ele existe e tem as permissões corretas.")"
 			sh_usage
 		fi
 	else
 		sh_usage
 	fi
 }
-
-function sh_set_qemu_common_options {
-	#   qemu_options+=(-drive id=disk,file=/archlive/qemu/hda.img,format=raw,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0)
-	#   qemu_options+=(-device virtio-scsi-pci,id=scsi1 -drive file=/archlive/qemu/hda.img,if=none,format=raw,discard=unmap,aio=native,cache=none,id=someid -device scsi-hd,drive=someid,bus=scsi0.0)
-	#	qemu_options+=(-drive file=/archlive/qemu/hdb.img,format=raw,media=disk)
-	#	qemu_options+=(-drive file=/archlive/qemu/hdc.img,format=raw,media=disk)
-	#	qemu_options+=(-drive file=/archlive/qemu/hdd.img,format=raw,media=disk)
-	qemu_options+=(-no-fd-bootchk)
-	qemu_options+=(-machine accel=kvm)
-	qemu_options+=(-cpu host)
-	qemu_options+=(-smp "$(nproc)")
-	#	qemu_options+=(-m ${xmem})
-	#   qemu_options+=(-name "$HOSTNAME")
-	qemu_options+=(-name 'chili-runimage')
-	#   qemu_options+=(-drive file=${1},if=none,id=disk1)
-	#   qemu_options+=(-device ide-hd,drive=disk1,bootindex=1)
-	#   qemu_options+=(-name archiso,process=archiso_0)
-	#   qemu_options+=(-device virtio-scsi-pci,id=scsi0)
-	#   qemu_options+=(-netdev user,id=net0)
-	#   qemu_options+=(-device e1000,netdev=net0)
-	#gpu
-	#	qemu_options+=(-vga std)				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
-	#  	qemu_options+=(-vga virtio)             # ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (virtio-gpu.ko)
-	#   qemu_options+=(-vga qxl) 				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (qxl.ko) ✓ windows driver
-	#	qemu_options+=(-vga cirrus)		        # ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (cirrus.ko)
-	#   qemu_options+=(-vga vmware)             # ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (virtio-gpu.ko)	#   qemu_options+=(-vga vmware)             # ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (virtio-gpu.ko)
-
-	#	qemu_options+=(-device virtio-vga)      # ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (virtio-gpu.ko)
-	#	qemu_options+=(-device qxl-vga)			# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (qxl.ko) ✓ windows driver
-	#	qemu_options+=(-device VGA)				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
-	#	qemu_options+=(-device cirrus-vga)		# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (cirrus.ko)
-	#	qemu_options+=(-device ati-vga)         # ✓ VGA compatível ✓ vgabios suporte ✗ sem suporte UEFI
-	#   qemu_options+=(-device virtio-gpu-pci virgl=on)  # ✗ not VGA compatible ✗ no vgabios support ✓ UEFI support (VirtioGpuDxe) ✓ linux driver (virtio-gpu.ko)
-	#   qemu_options+=(-device VGA,vgamem_mb=1024) # ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
-	#   qemu_options+=(-device virtio-gpu-pci)  # ✗ not VGA compatible ✗ no vgabios support ✓ UEFI support (VirtioGpuDxe) ✓ linux driver (virtio-gpu.ko)
-	#	qemu_options+=(-device bochs-display)	# ✗ not VGA compatible	✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
-	#	qemu_options+=(-device ramfb)			# ✗ não compatível com VGA ✓ vgabios suporte ✓ Suporte UEFI (QemuRamfbDxe)
-
-    #   qemu_options+=(-vga "$videodevice")
-    qemu_options+=(-device "$videodevice")
-
-	#display
-	#   qemu_options+=(-display sdl)
-	#   qemu_options+=(-display sdl,gl=on)
-	#   qemu_options+=(-display curses)
-	#   qemu_options+=(-display none)
-	#   qemu_options+=(-display gtk)
-	qemu_options+=(-display gtk,gl=on)
-	#   qemu_options+=(-display vnc=127.0.0.1:0)
-	qemu_options+=(-device intel-hda)
-	if [[ "$audioserver" = 'pulseaudio' ]]; then
-		#	qemu_options+=(-audiodev pa,id=snd0,server=localhost)
-		#   qemu_options+=(-audiodev pa,id=snd0,server=unix:/tmp/pulse-socket)
-		#   qemu_options+=(-audiodev pa,id=snd0,server=unix:${XDG_RUNTIME_DIR}/pulse/native,out.stream-name=foobar,in.stream-name=foobar)
-		qemu_options+=(-audiodev pa,id=snd0)
-	elif [[ "$audioserver" = 'alsa' ]]; then
-		qemu_options+=(-audiodev alsa,id=snd0)
-	else
-		qemu_options+=(-audiodev pipewire,id=snd0)
-	fi
-    qemu_options+=(-device hda-duplex,audiodev=snd0,mixer=off)
-	qemu_options+=(-rtc base=localtime,clock=host)
-	qemu_options+=(-device ich9-intel-hda)
-	qemu_options+=(-device hda-output,audiodev=snd0)
-	qemu_options+=(-global ICH9-LPC.disable_s3=1)
-	qemu_options+=(-machine type=q35,smm=on,accel=kvm,usb=on,pcspk-audiodev=snd0)
-	qemu_options+=(-serial stdio)
-}
-
-#				  	-netdev user,id=net0 \
-#				  	-device virtio-net-pci,netdev=net0 \
-#				  	-net nic,model=virtio \
-#				  	-net user \
 
 function sh_usage {
 	cat <<EOF
@@ -371,7 +360,7 @@ eval set -- "${opts[*]}"
 
 while test ${#opts[*]} -gt 0; do
 	case $1 in
-	-v|--video)
+	-v | --video)
 		if [[ $2 =~ ^(virtio-vga|virtio-gpu-pci|qxl-vga|VGA|cirrus-vga|ati-vga|virtio-gpu-pci|bochs-display|ramfb)?$ ]]; then
 			videodevice="$2"
 			shift
@@ -379,7 +368,7 @@ while test ${#opts[*]} -gt 0; do
 			die "$(gettext "Argumento inválido para -v. Use virtio-vga,virtio-gpu-pci,qxl-vga,VGA,cirrus-vga,ati-vga,virtio-gpu-pci,bochs-display ou ramfb")" >&2
 		fi
 		;;
-	-a|--audio)
+	-a | --audio)
 		if [[ $2 =~ ^(pulseaudio|alsa|pipewire)?$ ]]; then
 			audioserver="$2"
 			shift
@@ -387,25 +376,25 @@ while test ${#opts[*]} -gt 0; do
 			die "$(gettext "Argumento inválido para -a. Use pulseaudio, alsa ou pipewire")" >&2
 		fi
 		;;
-	-d|--drive)
+	-d | --drive)
 		if [[ -n $2 ]]; then
-			drive=1
+			drive=true
 			drive_path=$2
 			shift
 		else
 			die "$(gettext "Argumento inválido para --drive. Use formato device, como /dev/sdX (por exemplo).")" >&2
 		fi
 		;;
-	-u|--uefi)
-		uefi=1
+	-u | --uefi)
+		uefi=true
 		;;
-	-b|--bridge)
-		bridge=1
+	-b | --bridge)
+		bridge=true
 		;;
-	-n|--nocolor)
+	-n | --nocolor)
 		sh_unsetvarcolors
 		;;
-	-m|--memory)
+	-m | --memory)
 		if [[ $2 =~ ^[0-9]+[MG]?$ ]]; then
 			xmem=$2
 			shift
@@ -413,8 +402,8 @@ while test ${#opts[*]} -gt 0; do
 			die "$(gettext "Argumento inválido para -m. Use um formato como 16GB (por exemplo).")" >&2
 		fi
 		;;
-	-V|--version) sh_version ;;
-	-h|--help) sh_usage ;;
+	-V | --version) sh_version ;;
+	-h | --help) sh_usage ;;
 	--)
 		shift
 		break
@@ -434,25 +423,31 @@ sh_set_qemu_common_options
 if [[ $# > 0 ]]; then
 	#	sh_checkRoot
 	qemu_options+=(-m ${xmem})
-	if ((bridge)); then
+	if $bridge; then
 		random_mac_net0=$(python3 -c "import random; print(':'.join(['{:02x}'.format(random.randint(0, 255)) for _ in range(6)]))")
 		random_mac_net1=$(python3 -c "import random; print(':'.join(['{:02x}'.format(random.randint(0, 255)) for _ in range(6)]))")
 		#	echo $random_mac_net0
 		#	echo $random_mac_net1
-		qemu_options+=(-netdev bridge,id=net0,smb=$HOME)
-		qemu_options+=(-device e1000,netdev=net0)
-		#		qemu_options+=(-netdev bridge,id=net0,br=$iface_bridge)
-		#		qemu_options+=(-device e1000,netdev=net0,mac=$random_mac_net0)
-		#		qemu_options+=(-netdev bridge,id=net1,br=$iface_bridge)
-		#		qemu_options+=(-device e1000,netdev=net1,mac=$random_mac_net1)
+		#qemu_options+=(-netdev bridge,id=net0,smb=$HOME)
+		#qemu_options+=(-netdev bridge,id=net0)
+		#qemu_options+=(-device e1000,netdev=net0)
+		qemu_options+=(-netdev bridge,id=net0,br=$iface_bridge)
+		qemu_options+=(-device virtio-net-pci,netdev=net0)
+		#qemu_options+=(-device e1000,netdev=net0,mac=$random_mac_net0)
+		#qemu_options+=(-netdev bridge,id=net1,br=$iface_bridge)
+		#qemu_options+=(-device e1000,netdev=net1,mac=$random_mac_net1)
+		#qemu_options+=(-netdev tap,ifname=tap1,script=no,downscript=no,id=mynet0)
+		#qemu_options+=(-device virtio-net-device,netdev=mynet0,mac=92:7b:15:c3:4d:ec)
 	else
-		qemu_options+=(-netdev user,id=net0,smb=$HOME)
-		qemu_options+=(-device e1000,netdev=net0)
+		#	qemu_options+=(-netdev user,id=net0,smb=$HOME)
+		qemu_options+=(-netdev user,id=net0)
+		#qemu_options+=(-device e1000,netdev=net0)
+		qemu_options+=(-device virtio-net-pci,netdev=net0)
 	fi
-	if ((drive)); then
+	if $drive; then
 		qemu_options+=(-drive file=$drive_path,format=raw,media=disk)
 	fi
-	if ((uefi)); then
+	if $uefi; then
 		filerun_uefi "$@"
 	else
 		filerun_bios "$@"
diff --git a/mkvoid b/mkvoid
--- a/mkvoid
+++ b/mkvoid
@@ -37,11 +37,11 @@ shopt -s extglob
 
 function sh_configure {
 	##########################################################
-	declare -g distro_name='MAZON'
-	declare -g distro_de='xfce'
+	declare -g distro_name='chililinux'
+	declare -g distro_de='base'
 	declare -g lfs_version='live'
 	declare -g lfs_root='/lfs'
-	declare -g lfs_basename='mazon'
+	declare -g lfs_basename='lfs_base'
 	declare -g bootloader='syslinux'
 	declare -g initcpio='dracut' # mkinitcpio # mkinitramfs
 	##########################################################
@@ -60,7 +60,7 @@ function sh_configure {
 	declare -g date_ymd=$(date +"%Y.%m.%d")
 	declare -g VOL_ID="${distro_name}_${date_ym}"
 	declare -g capitalized_distro_name="${distro_name,,}"
-			   capitalized_distro_name="${capitalized_distro_name^}"
+			       capitalized_distro_name="${capitalized_distro_name^}"
 	##########################################################
 	sh_choosekernel
 	sh_choosebootloader
@@ -80,7 +80,10 @@ function sh_configure {
 		;;
 	esac
 	##########################################################
-	declare -g OUTPUT_ISO="$distro_name-$lfs_basename-$lfs_version-$distro_de-$kernel_version-$ARCH-$date_ymd.iso"
+  #void-live-cinnamon-custom-x86_64-6.6.65_1-20241218-0437.iso
+  #chililinux-lfs_base-live-base-6.1.28-lts-chili-x86_64-2024.12.18.is
+	#declare -g OUTPUT_ISO="$distro_name-$lfs_basename-$lfs_version-$distro_de-$kernel_version-$ARCH-$date_ymd.iso"
+	declare -g OUTPUT_ISO="$distro_name-$lfs_version-$distro_de-$lfs_basename-$kernel_version-$ARCH-$date_ymd.iso"
 	declare -g KERNEL="${ORIGEM}/boot/vmlinuz-$kernel_version"
 	declare -g INITRD="${ORIGEM}/boot/initrd-$kernel_version.img"
 	[[ ! -e $INITRD ]] && INITRD="${ORIGEM}/boot/initramfs-$kernel_version.img"
@@ -132,7 +135,7 @@ function sh_msg_warning {
 function sh_msg_error {
 	local _msg="${1}"
 	local _error="${2}"
-	printf '[%s] ERROR: %s\n' "${_APP_}" "${_msg}" >&2
+	printf "${cyan}[%s] ${red}ERROR: %s\n" "${_APP_}" "${_msg}" >&2
 	if ((_error > 0)); then
 		exit "${_error}"
 	fi
